GET http://localhost:8080/users/list

###
POST http://localhost:8080/users/signup
Content-Type: application/json

{
  "email": "user1@example.com",
  "password": "123456"
}

###
GET http://localhost:8080/users/qrcode?email=user1@example.com
Content-Type: image/png

###
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email": "user1@example.com",
  "password": "123456",
  "authenticationCode": "000000"
}
